/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NarrowRouteImport } from './routes/_narrow'
import { Route as WideRouteImport } from './routes/_wide'
import { Route as WideFindScentRouteImport } from './routes/_wide.find-scent'
import { Route as WideIndexRouteImport } from './routes/_wide.index'
import { Route as WideMyPageRouteImport } from './routes/_wide.my-page'
import { Route as WideNotRealRouteImport } from './routes/_wide.not-real'

const WideRoute = WideRouteImport.update({
  id: '/_wide',
  getParentRoute: () => rootRouteImport,
} as any)
const NarrowRoute = NarrowRouteImport.update({
  id: '/_narrow',
  getParentRoute: () => rootRouteImport,
} as any)
const WideIndexRoute = WideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WideRoute,
} as any)
const WideNotRealRoute = WideNotRealRouteImport.update({
  id: '/not-real',
  path: '/not-real',
  getParentRoute: () => WideRoute,
} as any)
const WideMyPageRoute = WideMyPageRouteImport.update({
  id: '/my-page',
  path: '/my-page',
  getParentRoute: () => WideRoute,
} as any)
const WideFindScentRoute = WideFindScentRouteImport.update({
  id: '/find-scent',
  path: '/find-scent',
  getParentRoute: () => WideRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WideIndexRoute
  '/find-scent': typeof WideFindScentRoute
  '/my-page': typeof WideMyPageRoute
  '/not-real': typeof WideNotRealRoute
  '/find-scent/keyword': typeof WideFindScentKeywordRoute
  '/find-scent/photo': typeof WideFindScentPhotoRoute
  '/find-scent/survey': typeof WideFindScentSurveyRoute
  '/find-scent/': typeof WideFindScentIndexRoute
}
export interface FileRoutesByTo {
  '/find-scent': typeof WideFindScentRoute
  '/my-page': typeof WideMyPageRoute
  '/not-real': typeof WideNotRealRoute
  '/scent-keyword': typeof WideScentKeywordRoute
  '/scent-photo': typeof WideScentPhotoRoute
  '/scent-survey': typeof WideScentSurveyRoute
  '/': typeof WideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_narrow': typeof NarrowRouteWithChildren
  '/_wide': typeof WideRouteWithChildren
  '/_wide/find-scent': typeof WideFindScentRoute
  '/_wide/my-page': typeof WideMyPageRoute
  '/_wide/not-real': typeof WideNotRealRoute
  '/_wide/': typeof WideIndexRoute
  '/_wide/find-scent/keyword': typeof WideFindScentKeywordRoute
  '/_wide/find-scent/photo': typeof WideFindScentPhotoRoute
  '/_wide/find-scent/survey': typeof WideFindScentSurveyRoute
  '/_wide/find-scent/': typeof WideFindScentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/find-scent'
    | '/my-page'
    | '/not-real'
    | '/find-scent/keyword'
    | '/find-scent/photo'
    | '/find-scent/survey'
    | '/find-scent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/find-scent'
    | '/my-page'
    | '/not-real'
    | '/scent-keyword'
    | '/scent-photo'
    | '/scent-survey'
    | '/'
  id:
    | '__root__'
    | '/_narrow'
    | '/_wide'
    | '/_narrow/signup'
    | '/_wide/find-scent'
    | '/_wide/my-page'
    | '/_wide/not-real'
    | '/_wide/'
    | '/_wide/find-scent/keyword'
    | '/_wide/find-scent/photo'
    | '/_wide/find-scent/survey'
    | '/_wide/find-scent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NarrowRoute: typeof NarrowRouteWithChildren
  WideRoute: typeof WideRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_wide': {
      id: '/_wide'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_narrow': {
      id: '/_narrow'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NarrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wide/': {
      id: '/_wide/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WideIndexRouteImport
      parentRoute: typeof WideRoute
    }
    '/_wide/not-real': {
      id: '/_wide/not-real'
      path: '/not-real'
      fullPath: '/not-real'
      preLoaderRoute: typeof WideNotRealRouteImport
      parentRoute: typeof WideRoute
    }
    '/_wide/my-page': {
      id: '/_wide/my-page'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof WideMyPageRouteImport
      parentRoute: typeof WideRoute
    }
    '/_wide/find-scent': {
      id: '/_wide/find-scent'
      path: '/find-scent'
      fullPath: '/find-scent'
      preLoaderRoute: typeof WideFindScentRouteImport
      parentRoute: typeof WideRoute
    }
  }
}

interface WideRouteChildren {
  WideFindScentRoute: typeof WideFindScentRouteWithChildren
  WideMyPageRoute: typeof WideMyPageRoute
  WideNotRealRoute: typeof WideNotRealRoute
  WideIndexRoute: typeof WideIndexRoute
}

const WideRouteChildren: WideRouteChildren = {
  WideFindScentRoute: WideFindScentRouteWithChildren,
  WideMyPageRoute: WideMyPageRoute,
  WideNotRealRoute: WideNotRealRoute,
  WideIndexRoute: WideIndexRoute,
}

const WideRouteWithChildren = WideRoute._addFileChildren(WideRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  NarrowRoute: NarrowRouteWithChildren,
  WideRoute: WideRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
