/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WideRouteImport } from './routes/_wide'
import { Route as NarrowRouteImport } from './routes/_narrow'
import { Route as WideIndexRouteImport } from './routes/_wide.index'
import { Route as WideScentSurveyRouteImport } from './routes/_wide.scent-survey'
import { Route as WideScentKeywordRouteImport } from './routes/_wide.scent-keyword'
import { Route as WideNotRealRouteImport } from './routes/_wide.not-real'
import { Route as WideMyPageRouteImport } from './routes/_wide.my-page'
import { Route as WideFindScentRouteImport } from './routes/_wide.find-scent'
import { Route as NarrowSignupIndexRouteImport } from './routes/_narrow.signup.index'

const WideRoute = WideRouteImport.update({
  id: '/_wide',
  getParentRoute: () => rootRouteImport,
} as any)
const NarrowRoute = NarrowRouteImport.update({
  id: '/_narrow',
  getParentRoute: () => rootRouteImport,
} as any)
const WideIndexRoute = WideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WideRoute,
} as any)
const WideScentSurveyRoute = WideScentSurveyRouteImport.update({
  id: '/scent-survey',
  path: '/scent-survey',
  getParentRoute: () => WideRoute,
} as any)
const WideScentKeywordRoute = WideScentKeywordRouteImport.update({
  id: '/scent-keyword',
  path: '/scent-keyword',
  getParentRoute: () => WideRoute,
} as any)
const WideNotRealRoute = WideNotRealRouteImport.update({
  id: '/not-real',
  path: '/not-real',
  getParentRoute: () => WideRoute,
} as any)
const WideMyPageRoute = WideMyPageRouteImport.update({
  id: '/my-page',
  path: '/my-page',
  getParentRoute: () => WideRoute,
} as any)
const WideFindScentRoute = WideFindScentRouteImport.update({
  id: '/find-scent',
  path: '/find-scent',
  getParentRoute: () => WideRoute,
} as any)
const NarrowSignupIndexRoute = NarrowSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => NarrowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WideIndexRoute
  '/find-scent': typeof WideFindScentRoute
  '/my-page': typeof WideMyPageRoute
  '/not-real': typeof WideNotRealRoute
  '/scent-keyword': typeof WideScentKeywordRoute
  '/scent-survey': typeof WideScentSurveyRoute
  '/signup/': typeof NarrowSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WideIndexRoute
  '/find-scent': typeof WideFindScentRoute
  '/my-page': typeof WideMyPageRoute
  '/not-real': typeof WideNotRealRoute
  '/scent-keyword': typeof WideScentKeywordRoute
  '/scent-survey': typeof WideScentSurveyRoute
  '/signup': typeof NarrowSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_narrow': typeof NarrowRouteWithChildren
  '/_wide': typeof WideRouteWithChildren
  '/_wide/find-scent': typeof WideFindScentRoute
  '/_wide/my-page': typeof WideMyPageRoute
  '/_wide/not-real': typeof WideNotRealRoute
  '/_wide/scent-keyword': typeof WideScentKeywordRoute
  '/_wide/scent-survey': typeof WideScentSurveyRoute
  '/_wide/': typeof WideIndexRoute
  '/_narrow/signup/': typeof NarrowSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find-scent'
    | '/my-page'
    | '/not-real'
    | '/scent-keyword'
    | '/scent-survey'
    | '/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/find-scent'
    | '/my-page'
    | '/not-real'
    | '/scent-keyword'
    | '/scent-survey'
    | '/signup'
  id:
    | '__root__'
    | '/_narrow'
    | '/_wide'
    | '/_wide/find-scent'
    | '/_wide/my-page'
    | '/_wide/not-real'
    | '/_wide/scent-keyword'
    | '/_wide/scent-survey'
    | '/_wide/'
    | '/_narrow/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NarrowRoute: typeof NarrowRouteWithChildren
  WideRoute: typeof WideRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_wide': {
      id: '/_wide'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_narrow': {
      id: '/_narrow'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NarrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wide/': {
      id: '/_wide/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WideIndexRouteImport
      parentRoute: typeof WideRoute
    }
    '/_wide/scent-survey': {
      id: '/_wide/scent-survey'
      path: '/scent-survey'
      fullPath: '/scent-survey'
      preLoaderRoute: typeof WideScentSurveyRouteImport
      parentRoute: typeof WideRoute
    }
    '/_wide/scent-keyword': {
      id: '/_wide/scent-keyword'
      path: '/scent-keyword'
      fullPath: '/scent-keyword'
      preLoaderRoute: typeof WideScentKeywordRouteImport
      parentRoute: typeof WideRoute
    }
    '/_wide/not-real': {
      id: '/_wide/not-real'
      path: '/not-real'
      fullPath: '/not-real'
      preLoaderRoute: typeof WideNotRealRouteImport
      parentRoute: typeof WideRoute
    }
    '/_wide/my-page': {
      id: '/_wide/my-page'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof WideMyPageRouteImport
      parentRoute: typeof WideRoute
    }
    '/_wide/find-scent': {
      id: '/_wide/find-scent'
      path: '/find-scent'
      fullPath: '/find-scent'
      preLoaderRoute: typeof WideFindScentRouteImport
      parentRoute: typeof WideRoute
    }
    '/_narrow/signup/': {
      id: '/_narrow/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof NarrowSignupIndexRouteImport
      parentRoute: typeof NarrowRoute
    }
  }
}

interface NarrowRouteChildren {
  NarrowSignupIndexRoute: typeof NarrowSignupIndexRoute
}

const NarrowRouteChildren: NarrowRouteChildren = {
  NarrowSignupIndexRoute: NarrowSignupIndexRoute,
}

const NarrowRouteWithChildren =
  NarrowRoute._addFileChildren(NarrowRouteChildren)

interface WideRouteChildren {
  WideFindScentRoute: typeof WideFindScentRoute
  WideMyPageRoute: typeof WideMyPageRoute
  WideNotRealRoute: typeof WideNotRealRoute
  WideScentKeywordRoute: typeof WideScentKeywordRoute
  WideScentSurveyRoute: typeof WideScentSurveyRoute
  WideIndexRoute: typeof WideIndexRoute
}

const WideRouteChildren: WideRouteChildren = {
  WideFindScentRoute: WideFindScentRoute,
  WideMyPageRoute: WideMyPageRoute,
  WideNotRealRoute: WideNotRealRoute,
  WideScentKeywordRoute: WideScentKeywordRoute,
  WideScentSurveyRoute: WideScentSurveyRoute,
  WideIndexRoute: WideIndexRoute,
}

const WideRouteWithChildren = WideRoute._addFileChildren(WideRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  NarrowRoute: NarrowRouteWithChildren,
  WideRoute: WideRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
