/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WideRouteImport } from './routes/_wide'
import { Route as NarrowRouteImport } from './routes/_narrow'
import { Route as WideIndexRouteImport } from './routes/_wide.index'
import { Route as WideNotRealRouteImport } from './routes/_wide.not-real'
import { Route as WideMyPageRouteImport } from './routes/_wide.my-page'
import { Route as WideFindScentRouteImport } from './routes/_wide.find-scent'
import { Route as NarrowSignupRouteImport } from './routes/_narrow.signup'
import { Route as WideFindScentIndexRouteImport } from './routes/_wide.find-scent.index'
import { Route as WideFindScentSurveyRouteImport } from './routes/_wide.find-scent.survey'
import { Route as WideFindScentPhotoRouteImport } from './routes/_wide.find-scent.photo'
import { Route as WideFindScentKeywordRouteImport } from './routes/_wide.find-scent.keyword'

const WideRoute = WideRouteImport.update({
  id: '/_wide',
  getParentRoute: () => rootRouteImport,
} as any)
const NarrowRoute = NarrowRouteImport.update({
  id: '/_narrow',
  getParentRoute: () => rootRouteImport,
} as any)
const WideIndexRoute = WideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WideRoute,
} as any)
const WideNotRealRoute = WideNotRealRouteImport.update({
  id: '/not-real',
  path: '/not-real',
  getParentRoute: () => WideRoute,
} as any)
const WideMyPageRoute = WideMyPageRouteImport.update({
  id: '/my-page',
  path: '/my-page',
  getParentRoute: () => WideRoute,
} as any)
const WideFindScentRoute = WideFindScentRouteImport.update({
  id: '/find-scent',
  path: '/find-scent',
  getParentRoute: () => WideRoute,
} as any)
const NarrowSignupRoute = NarrowSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => NarrowRoute,
} as any)
const WideFindScentIndexRoute = WideFindScentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WideFindScentRoute,
} as any)
const WideFindScentSurveyRoute = WideFindScentSurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => WideFindScentRoute,
} as any)
const WideFindScentPhotoRoute = WideFindScentPhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => WideFindScentRoute,
} as any)
const WideFindScentKeywordRoute = WideFindScentKeywordRouteImport.update({
  id: '/keyword',
  path: '/keyword',
  getParentRoute: () => WideFindScentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WideIndexRoute
  '/signup': typeof NarrowSignupRoute
  '/find-scent': typeof WideFindScentRouteWithChildren
  '/my-page': typeof WideMyPageRoute
  '/not-real': typeof WideNotRealRoute
  '/find-scent/keyword': typeof WideFindScentKeywordRoute
  '/find-scent/photo': typeof WideFindScentPhotoRoute
  '/find-scent/survey': typeof WideFindScentSurveyRoute
  '/find-scent/': typeof WideFindScentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WideIndexRoute
  '/signup': typeof NarrowSignupRoute
  '/my-page': typeof WideMyPageRoute
  '/not-real': typeof WideNotRealRoute
  '/find-scent/keyword': typeof WideFindScentKeywordRoute
  '/find-scent/photo': typeof WideFindScentPhotoRoute
  '/find-scent/survey': typeof WideFindScentSurveyRoute
  '/find-scent': typeof WideFindScentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_narrow': typeof NarrowRouteWithChildren
  '/_wide': typeof WideRouteWithChildren
  '/_narrow/signup': typeof NarrowSignupRoute
  '/_wide/find-scent': typeof WideFindScentRouteWithChildren
  '/_wide/my-page': typeof WideMyPageRoute
  '/_wide/not-real': typeof WideNotRealRoute
  '/_wide/': typeof WideIndexRoute
  '/_wide/find-scent/keyword': typeof WideFindScentKeywordRoute
  '/_wide/find-scent/photo': typeof WideFindScentPhotoRoute
  '/_wide/find-scent/survey': typeof WideFindScentSurveyRoute
  '/_wide/find-scent/': typeof WideFindScentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/find-scent'
    | '/my-page'
    | '/not-real'
    | '/find-scent/keyword'
    | '/find-scent/photo'
    | '/find-scent/survey'
    | '/find-scent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/my-page'
    | '/not-real'
    | '/find-scent/keyword'
    | '/find-scent/photo'
    | '/find-scent/survey'
    | '/find-scent'
  id:
    | '__root__'
    | '/_narrow'
    | '/_wide'
    | '/_narrow/signup'
    | '/_wide/find-scent'
    | '/_wide/my-page'
    | '/_wide/not-real'
    | '/_wide/'
    | '/_wide/find-scent/keyword'
    | '/_wide/find-scent/photo'
    | '/_wide/find-scent/survey'
    | '/_wide/find-scent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NarrowRoute: typeof NarrowRouteWithChildren
  WideRoute: typeof WideRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_wide': {
      id: '/_wide'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_narrow': {
      id: '/_narrow'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NarrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wide/': {
      id: '/_wide/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WideIndexRouteImport
      parentRoute: typeof WideRoute
    }
    '/_wide/not-real': {
      id: '/_wide/not-real'
      path: '/not-real'
      fullPath: '/not-real'
      preLoaderRoute: typeof WideNotRealRouteImport
      parentRoute: typeof WideRoute
    }
    '/_wide/my-page': {
      id: '/_wide/my-page'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof WideMyPageRouteImport
      parentRoute: typeof WideRoute
    }
    '/_wide/find-scent': {
      id: '/_wide/find-scent'
      path: '/find-scent'
      fullPath: '/find-scent'
      preLoaderRoute: typeof WideFindScentRouteImport
      parentRoute: typeof WideRoute
    }
    '/_narrow/signup': {
      id: '/_narrow/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof NarrowSignupRouteImport
      parentRoute: typeof NarrowRoute
    }
    '/_wide/find-scent/': {
      id: '/_wide/find-scent/'
      path: '/'
      fullPath: '/find-scent/'
      preLoaderRoute: typeof WideFindScentIndexRouteImport
      parentRoute: typeof WideFindScentRoute
    }
    '/_wide/find-scent/survey': {
      id: '/_wide/find-scent/survey'
      path: '/survey'
      fullPath: '/find-scent/survey'
      preLoaderRoute: typeof WideFindScentSurveyRouteImport
      parentRoute: typeof WideFindScentRoute
    }
    '/_wide/find-scent/photo': {
      id: '/_wide/find-scent/photo'
      path: '/photo'
      fullPath: '/find-scent/photo'
      preLoaderRoute: typeof WideFindScentPhotoRouteImport
      parentRoute: typeof WideFindScentRoute
    }
    '/_wide/find-scent/keyword': {
      id: '/_wide/find-scent/keyword'
      path: '/keyword'
      fullPath: '/find-scent/keyword'
      preLoaderRoute: typeof WideFindScentKeywordRouteImport
      parentRoute: typeof WideFindScentRoute
    }
  }
}

interface NarrowRouteChildren {
  NarrowSignupRoute: typeof NarrowSignupRoute
}

const NarrowRouteChildren: NarrowRouteChildren = {
  NarrowSignupRoute: NarrowSignupRoute,
}

const NarrowRouteWithChildren =
  NarrowRoute._addFileChildren(NarrowRouteChildren)

interface WideFindScentRouteChildren {
  WideFindScentKeywordRoute: typeof WideFindScentKeywordRoute
  WideFindScentPhotoRoute: typeof WideFindScentPhotoRoute
  WideFindScentSurveyRoute: typeof WideFindScentSurveyRoute
  WideFindScentIndexRoute: typeof WideFindScentIndexRoute
}

const WideFindScentRouteChildren: WideFindScentRouteChildren = {
  WideFindScentKeywordRoute: WideFindScentKeywordRoute,
  WideFindScentPhotoRoute: WideFindScentPhotoRoute,
  WideFindScentSurveyRoute: WideFindScentSurveyRoute,
  WideFindScentIndexRoute: WideFindScentIndexRoute,
}

const WideFindScentRouteWithChildren = WideFindScentRoute._addFileChildren(
  WideFindScentRouteChildren,
)

interface WideRouteChildren {
  WideFindScentRoute: typeof WideFindScentRouteWithChildren
  WideMyPageRoute: typeof WideMyPageRoute
  WideNotRealRoute: typeof WideNotRealRoute
  WideIndexRoute: typeof WideIndexRoute
}

const WideRouteChildren: WideRouteChildren = {
  WideFindScentRoute: WideFindScentRouteWithChildren,
  WideMyPageRoute: WideMyPageRoute,
  WideNotRealRoute: WideNotRealRoute,
  WideIndexRoute: WideIndexRoute,
}

const WideRouteWithChildren = WideRoute._addFileChildren(WideRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  NarrowRoute: NarrowRouteWithChildren,
  WideRoute: WideRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
